### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by vade** [aquietlife/whisp#10]
Hi!

Firstly, this is awesome! Thank you for sharing this work and the idea is lovely!

I am curious, what is the license of this project? I ask as an OSS developer looking to implement something similar into a project of mine : [Synopsis](http://github.com/synopsis) - and was curious if using a custom trained model into my inference passes is ok? 

Thank you again!

**Comment by johanndiedrick** [comment]
Hi @vade 

Thanks for reaching out and for the kind words about the project :) I'm glad you like it!

I just added an MIT license for the project, so please have at it!

https://github.com/aquietlife/whisp/blob/master/LICENSE

If you're able to implement something similar into Synopsis, please let me know, I'd love to see how this kind of work takes shape in other forms.

Thanks again for your interest!!! :)

**Comment by vade** [comment]
Thanks, thats fantastic news. Appreciate the follow up!
